name: 'Docker swarm stack deploy'
description: 'Docker stack deployment using swarmpit/portainer api'
author: 'Pradeep Mishra'

branding:
  icon: 'package'
  color: 'green'

# Define your inputs here.
inputs:
  host:
    description: 'Swarmpit/Portainer API FQDN'
    required: true
  api-token:
    description: 'Swarmpit/Portainer API Token'
    required: true
  stack:
    description: 'Docker swarm stack name'
    required: true
  client:
    description: 'Choose on of the supported client'
    type: choice
    options:
      - swarmpit
      - portainer
    required: true
  action:
    description: 'Choose deploy or delete'
    type: choice
    options:
      - deploy
      - delete
    required: true
  compose:
    description: 'Docker compose file name ( only required for deploy )'
    required: false
  endPointId:
    description:
      'Portainer endpoint id ( only required if client is portainer )'
    required: false
  swarmId:
    description:
      'Docker swarm cluster id ( only required if client is portainer )'
    required: false

runs:
  using: node20
  main: dist/index.js
